language: python
python:
   - "2.7"
before_install:
   # Move out of git directory to build root.
   - deactivate
   - cd ../..
   - pwd
install:
   # Download and extract the prebuilt binary.
   - wget -O nanshe-package.tgz https://www.dropbox.com/s/qhy2lhsk0ioge0p/nanshe-package.tgz?dl=0
   - tar -xzf nanshe-package.tgz
   - ls
   - rm -rf nanshe-package.tgz
   # Update all modules
   - cd nanshe-package/src/ilastik
   - cd ilastik; git remote set-url origin https://github.com/ilastik/ilastik ; git checkout master ; git fetch ; git reset --hard origin/master ; cd ..
   - cd lazyflow; git remote set-url origin https://github.com/ilastik/lazyflow ; git checkout master ; git fetch ; git reset --hard origin/master ; cd ..
   - cd volumina; git remote set-url origin https://github.com/ilastik/volumina ; git checkout master ; git fetch ; git reset --hard origin/master ; cd ..
   - git pull; git pull --recurse-submodules
   # Replace the src in the prebuilt binary with the one TravisCI cloned for us.
   - rm -rf ilastik
   - mv ../../../$TRAVIS_REPO_SLUG ilastik
   # Won't recognize setup.cfg unless we are in the source directory.
   - cd ilastik
script:
   # Run tests. Skip 3D tests as they take too long (~1hr).
   - ../../../bin/exec.sh ../../../bin/python ../../../bin/nosetests -a '!3D' tests/
# Use container format for TravisCI to avoid termination due to insufficient resources.
sudo: false
